### ISSUE TITLE
Cannot create session 'GameSession': session already exists

### ISSUE THREAD

**Issue by Parkjoungwan** [project-d-p/Client#31]
# 문제 설명

패키징 후, 로비 레벨에서 세션을 생성해 매칭로비로 이동하려고 할 때.

다음과 같은 에러 로그와 함께 세션 생성에 실패함

```
[2024.07.06-08.23.26:346][782]LogOnlineSession: Warning: STEAM: Cannot create session 'GameSession': session already exists.
[2024.07.06-08.23.26:346][782]LogTemp: Error: Failed to create session
```

# 예상되는 행동

세션 생성 후에, 매칭로비로 이동

# 필요한 조치

- 왜 “GameSession”이라는 세션이 생성되는지 확인
- 해당 중복 세션 로직이 발생하는지 확인 후 조치

**Comment by Parkjoungwan** [comment]
[[Warning: STEAM: Cannot create session 'GameSession': session already exists](https://forums.unrealengine.com/t/warning-steam-cannot-create-session-gamesession-session-already-exists/422498/2)](https://forums.unrealengine.com/t/warning-steam-cannot-create-session-gamesession-session-already-exists/422498/2)

패키징 시, 게임에 포함되어야하는 맵 파일들을 포함하지 않아서 생기는 에러라는 글을 확인했습니다.
현재 MacOS에서 패키징은 성공적으로 되는데 실행 시에 검은화면만 떠서 해당 문제 확인이 어렵습니다.

<img width="1038" alt="스크린샷 2024-07-07 오후 1 10 54" src="https://github.com/project-d-p/Client/assets/48785968/8af1d7ed-722b-4929-8d21-a84b34af6c2c">

다음과 같이 ListofMaps에 MatchLobby 파일을 추가해주시고 다시 한 번 패키징 후 테스트 부탁드립니다.

**Comment by Parkjoungwan** [comment]
https://github.com/project-d-p/Client/commit/158cc1efd8a11d2758f1eb27adf32051ed553e17

**Comment by dkglee** [comment]
오홍 확인했습니다~
고생하셨습니다~!
