### ISSUE TITLE
widget_result, scoreVerticalBox can't found

### ISSUE THREAD

**Issue by Parkjoungwan** [project-d-p/Client#43]
<img width="941" alt="스크린샷 2024-07-15 오전 11 13 32" src="https://github.com/user-attachments/assets/a8a24ec4-02e7-4e68-b77c-578c7288e077">

# 이슈

- scoreVerticalBox 바인딩 위젯을 찾을 수 없다는 에러가 발생했습니다.

# 필요한 조치

- DPResultRoomWidget의 scoreVerticalBox 관련로직 수정
- 또는, widget_result 내에 바인딩될 수 있도록 위젯 내부 요소 수정이 필요해 보입니다.

**Comment by 0-9-10-12** [comment]
아예 방식을 바꿔서 자동으로 해결됐습니다 !
