### ISSUE TITLE
Monster Skeletal Mesh 크기 및 비율 조정 필요

### ISSUE THREAD

**Issue by Han-Sang-min** [project-d-p/Client#44]
## 문제 설명
- 현재 게임 내 특정 Monster의 skeletal mesh의 애니메이션이 없는 문제가 있습니다.
- Rabbit의 경우는 skeletal 경고와 함께 캐릭터의 mesh를 가져오지 못합니다.
- 문제 브랜치: feat/add-monsters-and-tweaks
## 문제를 가지는 몬스터
Rabbit - skeletal 경고
SaborTiger - Animation 문제
shepherd - Animation 문제
Skunk - Animation 문제

## 추가 고려사항
- Lobby Level에서 사용되는 동물들의 위치, 방향을 조절해야할 것 같습니다. 현재 벽아래로 Mesh가 들어가거나 공중에 뜨는 등의 문제가 있습니다.

## 스크린샷
![image](https://github.com/user-attachments/assets/dad81575-b1e8-4aad-a6a2-266090a1abb7)

**Comment by Han-Sang-min** [comment]
# 여전히 남은 문제
## 토끼
분명 BluePrint로 에셋을 로드하면 문제없이 나옵니다. (C++ 코드를 상속받은 BP입니다)
하지만 인게임에 들어갈 경우 에셋이 보이지 않습니다.

## 셰퍼드
마찬가지로 BluePrint에서는 동작하지만 실제 게임에서는 Mesh 크기가 이상한 문제가 있습니다.


# 테스트 방법
feat/add-monsters-and-tweaks 브랜치로 이동하셔서 InGame 플레이해보시면 됩니다.

# 스크린샷
<img src=https://github.com/user-attachments/assets/7d896825-83e1-44bc-9c69-4cf57844a186 width="50%" height="50%">
<img src=https://github.com/user-attachments/assets/763266e3-276a-4cd1-9abf-5b34bb7dccf5 width="50%" height="50%">

**Comment by 0-9-10-12** [comment]
문제되는 mesh들이 다른 동물들로 대체되었습니다
토끼, 셰퍼드 -> 카멜레온, 말
수정됨에 따라 해당 mesh 경로 설정을 수정해야합니다.
직업에 따른 수집 동물에 대해 추후 다시 이야기 해야할 것 같습니다.
